### PR TITLE
Tr/gpu refactor

### LINKED ISSUE #60: CodeCov secret token missing in RootSolvers, so coverage reports are not updated
The CodeCov secret token is missing in the CodeCov.yml and OS-UnitTests.yml files, so the code cov reports have been stale since 2022. 

Update CodeCov configuration and clean up CI to be consistent and reporting coverage correctly. 

==> Running upload-coverage
      ./codecov  upload-coverage --git-service github --sha 1dc3e7fdb0a5882d22aad30757759adc691f7f55 --file lcov.info --gcov-executable gcov
info - 2025-07-31 16:36:27,720 -- ci service found: github-actions
warning - 2025-07-31 16:36:27,729 -- No config file could be found. Ignoring config.
warning - 2025-07-31 16:36:27,759 -- xcrun is not installed or can't be found.
warning - 2025-07-31 16:36:27,763 -- No gcov data found.
warning - 2025-07-31 16:36:27,763 -- coverage.py is not installed or can't be found.
info - 2025-07-31 16:36:27,782 -- Found 1 coverage files to report
info - 2025-07-31 16:36:27,782 -- > /home/runner/work/RootSolvers.jl/RootSolvers.jl/lcov.info
info - 2025-07-31 16:36:28,104 -- Process Upload complete
error - 2025-07-31 16:36:28,104 -- Upload failed: {"message":"Token required because branch is protected"}
```

_Originally posted by @haakon-e in https://github.com/CliMA/RootSolvers.jl/pull/59#discussion_r2246107067_

### PR DESCRIPTION
**Pull request by imreddyTeja**
This PR closes #60 and addresses several points in #61 

What this PR does:

GPU Compatibility

- KernelAbstractions is removed from the tests
- `runtests_kernel.jl` is removed. GPU tests now are also run with `runtests.jl`. When the `CuArray` arg is supplied, the problems are expanded into `CuArrays` rather than `SArrays`. This prevents the gpu tests on buildkite from also running cpu tests (the scalar tests are still ran).
- Broadcasting already worked if the method was constructed as: `SecantMethod.(x0_cuarray, x1_cuarray)`. This adds support for constructing the method as ` SecantMethod(x0_cuarray, x1_cuarray)`, and adds tests for both.
- Update GPU example in docs

Other:
- Add allocations tests, and change broadcasting behavior to fix failures
- Add codecov token, bump action version
- Add depot path to buildkite pipeline to speed up buildkite initialization
- Add additional slurm memory to buildkite

TODO: 
- update codecov ref (it fails on this PR because it is comparing to main from 3 years ago)
- add to gpu docs if not clear

### CODE REVIEW

File: src/RootSolvers.jl [hunk 1]
```diff
@@ -868,32 +868,32 @@ end
...
     soltype::SolutionType,
     tol::Union{Nothing, AbstractTolerance} = nothing,
     maxiters::Int = 1_000,
-) where {FT <: FTypes, F}
+) where {FT <: FTypes, F, M <: RootSolvingMethod{FT}}
     if tol === nothing
         tol = default_tol(FT)
     end
-    return broadcast(
+    return Broadcast.broadcasted(
```
Comment (imreddyTeja) [inline src/RootSolvers.jl:893]: This change fixes the allocations when broadcasting. I believe that this change delays the evaluation of the broadcasted expression, and it is instead executed in a calling default `broadcast` scope. I'm not completely sure why that fixes allocations, but it may have something to do with not needing to re-inference the DestType

File: src/RootSolvers.jl [hunk 2]
```diff
@@ -868,32 +868,32 @@ end
 # Main entry point: Dispatch to specific method
 function find_zero(
     f::F,
-    method::RootSolvingMethod{FT},
+    method::M,
```
Comment (imreddyTeja) [inline src/RootSolvers.jl:871]: This change is only needed to support using the gpu in the following style:

```
method = SomeMethod(x0_cuarray, x1_cuarray)
find_zero.(f, method, CompactSolution())
```

File: src/RootSolvers.jl [hunk 3]
```diff
@@ -868,32 +868,32 @@ end
...
-    return find_zero(f, method, method_args(method)..., soltype, tol, maxiters)
+    return find_zero(f, M, method_args(method)..., soltype, tol, maxiters)
 end
 
 function Broadcast.broadcasted(
     ::typeof(find_zero),
     f::F,
-    method::RootSolvingMethod{FT},
+    method::M,
     soltype::SolutionType,
```
Comment (imreddyTeja) [inline src/RootSolvers.jl:886]: TODO: Add a default soltype here, because the non broadcasted entry point has one

Comment (tapios) [reply src/RootSolvers.jl:886]: Would make sense to make this `Compact...` by default

**Review by tapios — APPROVED** [review]
Looks great to me! Thank you, @imreddyTeja.

File: src/RootSolvers.jl (hunk 3 above)
Comment (imreddyTeja) [reply src/RootSolvers.jl]: Done
